### ISSUE TITLE
Link app

### ISSUE THREAD

**Issue by Changzw** [nataliq/TripCheckins#13]
how can I link the app to my Foursquare? :D

**Comment by Changzw** [comment]
i got it

**Comment by tomassliz** [comment]
@Changzw How did you link the app to Foursquare please? I filled in my client id and client_secret but I don't know the callback_uri.

**Comment by tomassliz** [comment]
I've already figured it out. You have to fill `Redirect URI(s)` for the app in Foursquare developers website and then fill it into the `foursquare_api_configuration.plist`. It needs to be same as the registered URL Types (tripcheckins://foursquare).

Everything is described in [Configuration/foursquare_api_configuration_instructions](https://github.com/nataliq/TripCheckins/blob/master/Configuration/foursquare_api_configuration_instructions)
